import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await page.goto("http://127.0.0.1:3000/index.html", { waitUntil: "networkidle" });
await page.locator('a[data-i18n="consultation_btn"]').click();
await page.waitForLoadState("networkidle");
const smoothTarget = page.url();
const form = page.locator("#contactForm");
await form.locator('button[type="submit"]').click();
const invalidError = await page.locator("#contactEmailError").textContent();
await page.evaluate(() => { window.sendContactMessage = async () => true; });
await page.locator("#contactName").fill("Dr. Test User");
await page.locator("#contactEmail").fill("test@example.com");
await page.locator("#contactMsg").fill("Please help with laboratory equipment.");
await form.locator('button[type="submit"]').click();
await page.waitForTimeout(100);
const successVisible = await page.locator("#contactSuccessModal").evaluate(el => !el.hidden);
console.log(JSON.stringify({ smoothTarget, invalidError, successVisible }));
await browser.close();
