import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto("http://127.0.0.1:3000/index.html", { waitUntil: "networkidle" });
const form = page.locator("#desktopProductSearch");
const input = form.locator('input[type="search"]');
await input.focus();
const suggestionsVisible = await form.locator("[data-search-suggestions]").isVisible();
const suggestionCount = await form.locator("[data-search-suggestion]").count();
await input.fill("Shimadzu");
const clearVisible = await form.locator("[data-search-clear]").isVisible();
await form.locator("[data-search-clear]").click();
const clearedValue = await input.inputValue();
await input.fill("Shimadzu");
const submitPromise = form.locator("button[type=submit]").click();
await page.waitForTimeout(60);
const loadingVisible = await form.locator(".search-submit-spinner").isVisible();
await submitPromise;
await page.waitForLoadState("networkidle");
console.log(JSON.stringify({ suggestionsVisible, suggestionCount, clearVisible, clearedValue, loadingVisible, url: page.url() }));
await browser.close();
